name: CI Pipeline - Docker Node.js

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar o Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Fazer build da imagem Docker
        run: docker build -t node-app .

      - name: Rodar container Docker
        run: docker run node-app
